// Centralized UI labels (can be localized easily)
window.LABELS = {
  static: {
    title: "VRP Demo",
    preset: "Preset",
    presetOne: "1 person (A)",
    presetThree: "3 persons (A,B,C)",
    speed: "Drive speed(km/h)",
    solverSeconds: "Solver seconds",
    solve: "Solve",
    targetCount: "Number of Target",
    apply: "Apply",
    labelToggle: "Display label",
    startDate: "Start date",
    singleDay: "Calc for single day",
    date: "Date",
    dateSelectAll: "Select All",
    dateSelectNone: "Clear All",
    legendRequired: "Required",
    legendOptional: "Option",
    legendBranch: "Branch",
    tabSchedule: "Schedule",
    tabCoords: "Target",
    tabRaw: "RAW",
  },
  tabs: { schedule: "Schedule", targets: "Target", raw: "RAW" },
  scheduleView: { list: "List", calendar: "Calendar" },
  calendarMode: { work: "Working time", full: "Full day" },
  scheduleHeaders: {
    date: "Date",
    driver: "Driver",
    seq: "Seq",
    target: "Target",
    arrival: "Arrival",
    departure: "Departure",
    travel: "Travel",
    stay: "Stay",
    timeWindow: "Time Window",
  },
  coordsHeaders: {
    id: "ID",
    lat: "Lat",
    lon: "Lon",
    stay: "Stay",
    required: "Required",
    timeWindow: "Time Window",
  },
  summary: {
    travel: "Total travel time",
    visits: "Total visit",
    unassigned: "Unassigned",
  },
};
